### PR TITLE
Add auto-installation script

### PR DESCRIPTION
**Pull request by Tsu-gu**
An attempt on an installation script that creates the config directory, adds in the example config file, places the binaries in their correct folders (/bin), and adds in a script launching mouseless with the --config flag.

### CODE REVIEW

**Comment by jbensmann** [comment]
Thanks for the contribution, I would like to merge it with some adjustments:
- consider the case when multiple devices are found, optimally insert all to the config file, but it would also be ok to simply take the first one (e.g. with `head -n1`) so that at least the config file is syntactically correct
- use `/usr/local/bin` which is intended for manually installed binaries
- use `/tmp/mouseless` instead of the home directory for temporary files

Do you want to have a look? Otherwise I could also merge it and then make the adjustments.

**Comment by Tsu-gu** [comment]
Is this what you had in mind?

**Comment by Tsu-gu** [comment]
So I've accidentally written a genious code. I plugged a keyboard into my laptop, and the keyboard variable detected the plugged in keyboard. Once un-plugged, the variable is back to the laptop keyboard.

**Comment by Tsu-gu** [comment]
We could set mouseless-execute to automatically detect the connected keyboards, and upon each launch it would detect whether an external one is plugged in, or if you are only using the laptop's one, and it would change it in the config file.... now how to implement that.

**Comment by Tsu-gu** [comment]
So I've come up with this idea. It's not ideal at all as it involves the user pasting commands into the terminal, but for some reason sed refuses to edit the config file if it's done directly like this `sed -i 's#$oldkeyboard#$newkeyboard#g' config.yaml`, but when you echo this output, the variables get replaced with the names of the keybaords, and once pasted into the terminal, it works as intented. I'm probably missing something important with sed.
```
#!/bin/bash

newkeyboard=$(ls /dev/input/by-id/*kbd* || ls /dev/input/by-path/*kbd* | head -n1)
oldkeyboard=$(cat /home/$USER/.config/mouseless/config.yaml | grep "/dev/input" | sed 's/- //')
echo "Copy this output and paste it into your terminal."
echo "====================================================="
echo "cd /home/$USER/.config/mouseless && sed -i 's#$oldkeyboard#$newkeyboard#g' config.yaml && sudo mouseless --config ~/.config/mouseless/config.yaml"
echo "====================================================="
```

**Comment by Tsu-gu** [comment]
Made it work, even tho I'm not pround of this at all. But hey, it does exactly what I wanted.
```
#!/bin/bash

newkeyboard=$(ls /dev/input/by-id/*kbd* || ls /dev/input/by-path/*kbd* | head -n1)
oldkeyboard=$(cat /home/$USER/.config/mouseless/config.yaml | grep "/dev/input" | sed 's/- //')

touch /home/$USER/.config/mouseless/hugeworkaround.sh
echo "#!/bin/bash 
cd /home/$USER/.config/mouseless && sed -i 's#$oldkeyboard#$newkeyboard#g' config.yaml && sudo mouseless --config ~/.config/mouseless/config.yaml" > /home/$USER/.config/mouseless/hugeworkaround.sh
chmod +x /home/$USER/.config/mouseless/hugeworkaround.sh
cd /home/$USER/.config/mouseless
sh hugeworkaround.sh
```

**Comment by jbensmann** [comment]
One can also specify multiple devices in the config file, and mouseless reads all that are currently available. If there is more logic needed I would like to put it in mouseless itself and not an external script, unless for special cases maybe. Some improvements I have been thinking about:
- if it cannot read any of the devces in the confg file, it could detect all available keyboards and ask the user which to use
- if the config file does not exist, create one and ask which device to use
- an option to read all keyboards it can detect

**Comment by Tsu-gu** [comment]
Interesting, didn't know mouseless accepts multiple keyboard names in the config. I will take a look when I get back home.

**Comment by jbensmann** [comment]
It looks good now, there are just some minor things I would change, but I merge it now and go over it again later.
Thanks again for your contribution!

**Pull request merged**
